(deftheme terhechte
  "MyThemeThings-Created 2013-08-05.")

(custom-theme-set-variables
 'terhechte
 '(ansi-color-names-vector ["#110F13" "#b13120" "#719f34" "#ceae3e" "#7c9fc9" "#7868b5" "#009090" "#F4EAD5"])
 '(ansi-term-color-vector [unspecified "#110F13" "#b13120" "#719f34" "#ceae3e" "#7c9fc9" "#7868b5" "#009090" "#F4EAD5"])
 '(cua-enable-cua-keys nil)
 '(current-language-environment "UTF-8")
 '(custom-safe-themes t)
 '(display-time-world-time-format "%A %d %B %R %Z (%z)")
 '(indent-tabs-mode nil)
 '(indicate-buffer-boundaries (quote right))
 '(inhibit-startup-screen t)
 '(initial-buffer-choice nil)
 '(initial-scratch-message nil)
 '(jshint-configuration-path "~/.jshintrc")
 '(linum-delay nil)
 '(linum-eager t)
 '(linum-format " %7d ")
 '(make-backup-files nil)
 '(safe-local-variable-values (quote ((eval when (fboundp (quote rainbow-mode)) (rainbow-mode 1)) (eval ignore-errors "Write-contents-functions is a buffer-local alternative to before-save-hook" (add-hook (quote write-contents-functions) (lambda nil (delete-trailing-whitespace) nil)) (require (quote whitespace)) "Sometimes the mode needs to be toggled off and on." (whitespace-mode 0) (whitespace-mode 1)) (whitespace-line-column . 80) (whitespace-style face trailing lines-tail) (require-final-newline . t))))
 '(scroll-bar-mode nil)
 '(send-mail-function (quote sendmail-send-it))
 '(tab-width 2)
 '(truncate-lines t)
 '(visible-bell t)
 '(yas-prompt-functions (quote (yas-dropdown-prompt yas/x-prompt yas/completing-prompt yas/ido-prompt yas/no-prompt)))
 '(zoneinfo-style-world-list (quote (("Australia/Sydney" "Sydney") ("Europe/London" "London") ("Thailand/Bangkok" "Bangkok") ("America/Vancouver" "Vancouver") ("America/Los_Angeles" "San Fransisco") ("America/New_York" "New York") ("Asia/Shanghai" "Shanghai") ("Asia/Tokyo" "Tokyo"))))
 '(global-visual-line-mode t)
 '(global-hl-line-mode nil)
 '(fringe-mode 4)
 '(display-time-mode nil)
 '(cua-mode t)
 '(column-number-mode t)
 '(blink-cursor-mode nil))

(custom-theme-set-faces
 'terhechte
 '(default ((t :height 140)))
 '(markdown-header-face ((t (:inherit font-lock-function-name-face :weight bold :family "Helvetica Neue"))))
 '(markdown-header-face-1 ((t (:inherit markdown-header-face :height 2.0))))
 '(markdown-header-face-2 ((t (:inherit markdown-header-face :height 1.9))))
 '(markdown-header-face-3 ((t (:inherit markdown-header-face :height 1.8))))
 '(markdown-header-face-4 ((t (:inherit markdown-header-face :height 1.7))))
 '(markdown-header-face-5 ((t (:inherit markdown-header-face :height 1.6))))
 '(markdown-header-face-6 ((t (:inherit markdown-header-face :height 1.5)))))

(provide-theme 'terhechte)
